default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  user: postgres
  password: ""

development:
  <<: *default
  database: registration_system_api_dev

test:
  <<: *default
  database: registration_system_api_test
